name: Hello Test #Имя проекта
on: push #Отрабатывать при пуше

jobs:
 build:   #Имя задачи (ID)
  runs-on: ubuntu-latest #На какой ОС запускать


  steps:
   - run: journalctl -k #Какая команда выполнится при пуше
  
